<h1>MSBios Permissions Acl Module</h1>

<ul>
    <?php if($this->acl->isAllowed('test', 'Level 1')):?>
    <li>
        Level 1
        <ul>
            <li>
                <?php if($this->acl->isAllowed('test', 'Level 1.1')):?>Level 1.1<?php endif; ?>
            </li>
            <li>
                <?php if($this->acl->isAllowed('test', 'Level 1.2')):?>
                Level 1.2
                <ul>
                    <li>
                        <?php if($this->acl->isAllowed('test', 'Level 1.2.1')):?>Level 1.2.1<?php endif; ?>
                    </li>
                    <li>
                        <?php if($this->acl->isAllowed('test', 'Level 1.2.2')):?>Level 1.2.2<?php endif; ?>
                    </li>
                    <li>
                        <?php if($this->acl->isAllowed('test', 'Level 1.2.3')):?>Level 1.2.3<?php endif; ?>
                    </li>
                </ul>
                <?php endif; ?>
            </li>
            <li>
                Level 1.3
            </li>
        </ul>
    </li>
    <?php endif; ?>
    <li>
        Level 2
    </li>
    <li>
        Level 3
    </li>
</ul>